# Generated by Django 3.2 on 2021-06-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(default='static/images/no-avatar.png', upload_to='uploads/teacher/avatar/%Y/%m/%d/'),
        ),
    ]
