# Generated by Django 3.2 on 2021-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw2', '0002_alter_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week_day',
            field=models.SmallIntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
    ]
