# Generated by Django 3.2 on 2021-11-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw2', '0003_alter_schedule_week_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_day',
            field=models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/teacher/avatar/%Y/%m/%d/'),
        ),
    ]
