# Generated by Django 3.2 on 2021-11-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw2', '0004_auto_20211114_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='whatsapp',
            field=models.CharField(max_length=16),
        ),
    ]
